# Generated by Django 3.2.5 on 2021-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='marketing', max_length=200),
            preserve_default=False,
        ),
    ]
