# Generated by Django 3.2.5 on 2021-08-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news',
            new_name='news_id',
        ),
    ]
