# Generated by Django 3.2.5 on 2021-08-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_news_comment_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news'),
        ),
    ]
