# Generated by Django 3.2.5 on 2021-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDFfile', models.FileField(upload_to='')),
                ('DOCfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('cash_flow_statement', models.TextField()),
                ('balance_sheet_statement', models.TextField()),
                ('income_statement', models.TextField()),
                ('brainstorming', models.TextField()),
                ('plannification', models.TextField()),
                ('hard_work', models.TextField()),
                ('success', models.TextField()),
            ],
        ),
    ]
